### ISSUE TITLE
Multi-Shot cast

### ISSUE THREAD

**Issue by Monteo** [Attero/Punschrulle#4]
Hey
https://forum.elysium-project.org/topic/38332-addon-yaht-yet-another-hunter-timer/#comment-349775

Rhena
Since the author of Punschrulle already has Aimed Shot support it might be a better idea to ask there first.

**Comment by Attero** [comment]
Incoming during the weekend.

**Comment by Attero** [comment]
Added options to toggle multishot and aimed shot castbars.
